version: '3'

services:
  orders-db:
    container_name: orders_db
    image: postgres:16.2
    restart: always
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
